package frc.robot.commands.chassis;

import edu.wpi.first.math.filter.SlewRateLimiter;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.math.SigmoidGenerator;
import frc.robot.subsystems.Chassis;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import static frc.robot.RobotContainer.mController;
import static java.lang.Math.cos;
import static java.lang.Math.sin;
import static java.lang.StrictMath.PI;

public class FieldCentricRecord extends CommandBase {

    // Auton Macro: For a more complete example, look at my 2021 code release

    // the basics: the joystick inputs to the drive are saved in a csv
    // which can then be played back to drive the robot in autonomous

    // if this works well, writing auton is as simple as asking your driver to drive the route
    // and saving the csv file in a special folder

    // however, there are some inconsistencies in testing that make me still iffy about using this at competition
    // especially for more complex paths.

    // I do think this could be a good alternative to path planning given enough time, effort, etc.

    // files generated by this can also be tweaked and reinserted.

    // I have not written a playback command yet, again there is a simpler example in the 2021 code release

    Chassis mChassis;

    FileWriter cWriter;

    public FieldCentricRecord(Chassis chassis) {
        mChassis = chassis;
        this.addRequirements(mChassis);

        try {
            // open a new recording file: name can be changed to denote different paths
            cWriter = new FileWriter(new File("/home/lvuser/recording.csv"));
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    private SlewRateLimiter fwdLimiter = new SlewRateLimiter(4.5);
    private SlewRateLimiter strLimiter = new SlewRateLimiter(4.5);
    private SlewRateLimiter rotLimiter = new SlewRateLimiter(4.5);

    private SigmoidGenerator responseCurve = new SigmoidGenerator(1.0);

    public double angle = mChassis.ahrs.getAngle();

    @Override
    public void initialize() {
        mChassis.comboFR.zero();
        mChassis.comboBR.zero();
        mChassis.comboFL.zero();
        mChassis.comboBL.zero();

        try {
            cWriter = new FileWriter("/home/lvuser/recording.csv");
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    @Override
    public void execute() {

        mChassis.feedAll();

        angle = -(mChassis.ahrs.getAngle() % 360);



        double axis0 = responseCurve.calculate(mController.getRawAxis(0));
        double axis1 = responseCurve.calculate(mController.getRawAxis(1));
        double axis4 = responseCurve.calculate(mController.getRawAxis(4));

        try {
            mChassis.runSwerve(fwdLimiter.calculate(axis1*cos(angle/360*(2*PI)) + axis0*sin(angle/360*(2*PI))),
                    strLimiter.calculate(axis1*sin(angle/360*(2*PI)) - axis0*cos(angle/360*(2*PI))),
                    rotLimiter.calculate(mController.getRawAxis(4)));
        } catch (Exception e) {
        }
//        System.out.println("Trying to drive");

        try {
            cWriter.append(mChassis.getData() + "\n");
        } catch (IOException e) {
            e.printStackTrace();
        }



    }

    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public void end(boolean isFinished) {
        try {
            cWriter.flush();
            cWriter.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        System.out.println("Writer closed");
    }

}


